services:
  db_service:
    image: mysql:8.0
    container_name: db_B7
    restart: always
    environment:
      MYSQL_DATABASE: kopikene_db
      MYSQL_USER: kopiapp
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  app_service:
    build: .
    container_name: app_B7
    restart: always
    environment:
      - DB_HOST=db_service
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=kopikene_db
      - APP_PORT=3000
    depends_on:
      - db_service

  nginx_service:
    image: nginx:alpine
    container_name: nginx_B7
    restart: always
    ports:
      - "8087:80"
    depends_on:
      - app_service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: